# =====================================================
# ENVIRONMENT SPECIFIC (Docker)
# =====================================================
server.port=${SERVER_PORT:8090}

# Redis Configuration
spring.data.redis.host=${SPRING_DATA_REDIS_HOST:redis}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT:6379}
spring.data.redis.timeout=2000ms
spring.data.redis.connect-timeout=5000

# =====================================================
# APPLICATION INFO
# =====================================================
spring.application.name=api-gateway

# Routes Configuration for API Gateway
#spring.cloud.gateway.routes[0].id=spb-app
#spring.cloud.gateway.routes[0].uri=http://localhost:8081
#spring.cloud.gateway.routes[0].predicates[0]=Path=/spb/**
#spring.cloud.gateway.routes[0].filters[0]=StripPrefix=1

# Eureka Client Configuration
#eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
spring.cloud.discovery.enabled=false
eureka.client.enabled=false
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# =====================================================
# Redis rate limiter config
# =====================================================
spring.cloud.gateway.httpclient.response-timeout=30s
spring.cloud.gateway.httpclient.connect-timeout=5000

# Bean configuration for RedisRateLimiter
spring.cloud.gateway.filter.request-rate-limiter.redis-rate-limiter.replenish-rate=10
spring.cloud.gateway.filter.request-rate-limiter.redis-rate-limiter.burst-capacity=20

# =====================================================
# LOGGING
# =====================================================
logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.com.example.api_gateway=DEBUG

# Actuator
management.endpoints.web.exposure.include=health,info,circuitbreakers,metrics,prometheus
management.endpoint.health.show-details=always